### ISSUE TITLE
Domains configured under /domains (json) are not loaded at gateway startup

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/graviteeio-access-management#78]
From https://github.com/gravitee-io/issues/issues/601

Hi,

We have a domain configured into the /domains dir.
This json file is not loaded at gateway startup.

Only the "default" domain "admin" is shown in logs and is stored in the Management repository (MongoDB DS).

Part of the configuration is below:
```
services:
  # Local registry service.
  # This registry is used to load domain definitions with json format from the file system.
  local:
    enabled: true
    path: ${gravitee.home}/domains # The path to domain descriptors
```
I can send the custom domain conf privately.

Am I missing something?
